@startuml L1_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Диаграмма системного контекста C4 (Level 1) — Система «Интеллектуальная библиотека»

Person(reader, "Читатель", "Ищет книги, подаёт заявки, голосует, общается на форумах")
Person(librarian, "Библиотекарь", "Обрабатывает заявки, ведёт фонд")
Person(admin, "Администратор", "Управляет системой, смотрит аналитику")

System(library, "Интеллектуальная библиотека", "Центральная система. Управляет фондом, обслуживает читателей, анализирует востребованность")

System_Ext(trends, "Сервис мировых трендов", "Внешний источник данных о популярных книгах (например, Open Library)")
System_Ext(email, "Сервис email-рассылок", "Уведомления читателям о готовности заявок, сроках возврата бумажных книг, ответах на форумах (Яндекс.Почта)")
System_Ext(payment, "Банковский эквайринг", "Принимает оплату штрафов за просрочку возврата бумажных книг (Тинькофф)")

Rel(reader, library, "Читает, обсуждает, участвует в формировании книжного фонда", "HTTPS")
Rel(librarian, library, "Регистрирует пользователя в системе и фиксирует, кто какую книгу взял", "HTTPS")
Rel(admin, library, "Управление системой (голосование), следит за аналитикой", "HTTPS")

Rel(library, trends, "Запрос данных о трендах", "REST API/HTTPS")
Rel(library, email, "Отправка уведомлений", "SMTP")
Rel(library, payment, "Запрос на приём платежа", "REST API/HTTPS")

@enduml